networks:
  default: development

dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.9.0
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.9.0

compiler:
  solc:
    version: 0.8.17
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.0"
      - "@openzeppelinupgrade=OpenZeppelin/openzeppelin-contracts-upgradeable@4.9.0"

autofetch_sources: true